### ISSUE TITLE
Using depracated methods

### ISSUE THREAD

**Issue by longnd** [ThinhMaiQuoc/NimbleChallengeFE#7]
## Issue
It isn't wrong, but there are several places in the applications use deprecated methods, for example:
- `puppeteer.page.waitfortimeout()`: https://pptr.dev/api/puppeteer.page.waitfortimeout 
https://github.com/ThinhMaiQuoc/NimbleChallengeBE/blob/a6c8b69c55b90f4bdfc7d714ca5c2a50a0aa752d/src/services/scraper.service.js#L19

- ReactDOM.render() is deprecated in React 18 (which is the version used in the application). It is quite obvious to see this warning during development process.

When starting a new project, it is recommended to avoid using deprecated features.

**Comment by ThinhMaiQuoc** [comment]
Hi Long,

Thank you for your valuable input regarding best practices in our projects. I've taken your advice and have made the following updates in the PRs:

1. Replaced deprecated `puppeteer.page.waitForTimeout()` with `setTimeout()` in the scraper service.

2. Addressed the deprecation of `ReactDOM.render()` in React 18 by using `createRoot()` for rendering.

**Comment by longnd** [comment]
Thank you for spending time on addressing the issue. I checked both PRs. This issue can now be closed.
